### ISSUE TITLE
0.prep.ud.sh broken if data directory not present

### ISSUE THREAD

**Issue by tomasohara** [machamp-nlp/machamp#13]
The 0.prep.ud.sh assumes the ./data directory exists. If not, it will fail:

```
Traceback (most recent call last):
  File "scripts/misc/cleanconl.py", line 32, in <module>
    rm_multiwords(path)
  File "scripts/misc/cleanconl.py", line 10, in rm_multiwords
    for line in open(path):
FileNotFoundError: [Errno 2] No such file or directory: 'data/ud-treebanks-v2.9.singleToken/*/*conllu
```

A simple fix is to use **mkdir -p** beforehand:
```
diff --git a/scripts/0.prep.ud.sh b/scripts/0.prep.ud.sh
index 2ea6a76..d19721a 100755
--- a/scripts/0.prep.ud.sh
+++ b/scripts/0.prep.ud.sh
@@ -2,6 +2,7 @@
 #wget https://lindat.mff.cuni.cz/repository/xmlui/bitstream/handle/11234/1-3687/ud-treebanks-v2.8.tgz
 wget https://lindat.mff.cuni.cz/repository/xmlui/bitstream/handle/11234/1-4611/ud-treebanks-v2.9.tgz
 tar -zxvf ud-treebanks-v2.9.tgz
+mkdir -p data
 mv ud-treebanks-v2.9 data
 cp -r data/ud-treebanks-v2.9 data/ud-treebanks-v2.9.singleToken
 python3 scripts/misc/cleanconl.py data/ud-treebanks-v2.9.singleToken/*/*conllu
```

**Comment by robvanderg** [comment]
I've updated the master and 0.4beta branch to fix this
