### ISSUE TITLE
error during inference

### ISSUE THREAD

**Issue by Lguyogiro** [machamp-nlp/machamp#34]
I am able to successfully train a multi-task model on a UD dataset. However, when I want to predict on un-annotated (i.e. conll-u format with ids and words, and the remaining 8 fields have "_") data using `predict.py`,  I get the following error:

```
Traceback (most recent call last):
  File "predict.py", line 55, in <module>
    predict_with_paths(model, input_path, output_path, args.dataset, args.batch_size, args.raw_text, device, args.conn, args.sep, args.threshold)
  File "/home/pughrob/machamp/machamp/predictor/predict.py", line 228, in predict_with_paths
    write_pred(out_file, batch, device, dev_dataset, model, data_config[dataset], raw_text, conn, sep)
  File "/home/pughrob/machamp/machamp/predictor/predict.py", line 194, in write_pred
    out_dict = model.get_output_labels(enc_batch['token_ids'], enc_batch['golds'], enc_batch['seg_ids'],
  File "/home/pughrob/machamp/machamp/model/machamp.py", line 478, in get_output_labels
    out_dict[task] = self.decoders[task].get_output_labels(mlm_out_task, task_word_mask, golds_task)
  File "/home/pughrob/machamp/machamp/model/seq_label_decoder.py", line 57, in get_output_labels
    logits = self.forward(mlm_out, mask, gold)['logits']
  File "/home/pughrob/machamp/machamp/model/seq_label_decoder.py", line 41, in forward
    self.metric.score(maxes, gold, self.vocabulary.inverse_namespaces[self.task])
  File "/home/pughrob/machamp/machamp/metrics/metric.py", line 63, in score
    self.metrics[metric].score(*kwargs)
  File "/home/pughrob/machamp/machamp/metrics/accuracy.py", line 20, in score
    self.cor += sum(preds==golds).item()
AttributeError: 'int' object has no attribute 'item'
```
the predict command I used is:
`python predict.py logs/path/to/model.pt .conllu pred_test.out --dataset <DATASET_NAME>--device 0`

If I evaluate on an annotated conllu file there are no problems, but when I replace those annotations (except the first two columns, id and form) with underscores, the above error occurs.

Any idea what could be going on here? I notice if I hard-code `golds=None` in `MachampSeqDecoder.forward()` the error is avoided...so it seems like it is expecting "golds" even for predictions?

Let me know if you have any ideas....its quite possible I'm overlooking something.

**Comment by robvanderg** [comment]
Hmm, I have just pushed a temporary fix; but we probably need something better. In the new commit, if there are only label -100 (PAD/UNK), we just count all incorrect. 

The problem is twofold; it is unclear when annotation is absent (for morphological tagging, only _'s or only unknown tokens can actually occur). Secondly,  it now ignores unknown labels and padding (UNK and PAD are the same in MaChAmp, to not get too many labels we never want to use) during the calculation of accuracy; which is also incorrect. I have to think a while about what the cleanest fix is for this. 

Ps. I would always recommend to use another implementation of metrics (which I also do myself) for "official" uses.

**Comment by robvanderg** [comment]
Yes, that could be done; I always sort of liked the automatic detection (simpler usage), but if there is no correct way that might be better. Note that the --raw_text option can also be used to predict without annotation, but then it doesn't read conllu files. For example:

head README.md > text-sample.txt
python3 predict.py logs/ewt/2023.10.16_09.11.27/model.pt out text-sample.txt sample-out.txt --raw_text

For UD evaluation I would use:
https://universaldependencies.org/conll18/evaluation.html 
Also note that I did compare our metrics to this a while ago, and results where the same for EWT. However, there could always be edge cases somewhere (like having unknown labels in test data for example)

**Comment by robvanderg** [comment]
Yes, it just splits on whitespaces for obtaining the tokens (of course the LM later tokenizes more things in most cases)

--no_labels sounds great, I would be very happy with a pull request!
