### ISSUE TITLE
Error scalar mix of the layers

### ISSUE THREAD

**Issue by ArijRB** [machamp-nlp/machamp#4]
Hello,

Using scalar mix to train the embedder layers fails with this error  

`Traceback (most recent call last):
  File "train.py", line 89, in <module>
    train(name, args.resume, args.dataset_configs, args.device, args.parameters_config, args.finetune)
  File "train.py", line 53, in train
    model, serialization_dir = util.train(train_params, name, resume, finetune)
  File "/machamp/util.py", line 147, in train
    model = train_model_from_file(config_path,
  File "/home/ariabi/.local/lib/python3.8/site-packages/allennlp/commands/train.py", line 170, in train_model_from_file
    return train_model(
  File "/home/ariabi/.local/lib/python3.8/site-packages/allennlp/commands/train.py", line 236, in train_model
    model = _train_worker(
  File "/home/ariabi/.local/lib/python3.8/site-packages/allennlp/commands/train.py", line 453, in _train_worker
    train_loop = TrainModel.from_params(
  File "/home/ariabi/.local/lib/python3.8/site-packages/allennlp/common/from_params.py", line 597, in from_params
    return retyped_subclass.from_params(
  File "/home/ariabi/.local/lib/python3.8/site-packages/allennlp/common/from_params.py", line 631, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/home/ariabi/.local/lib/python3.8/site-packages/allennlp/commands/train.py", line 714, in from_partial_objects
    trainer_ = trainer.construct(
  File "/home/ariabi/.local/lib/python3.8/site-packages/allennlp/common/lazy.py", line 58, in construct
    return self._constructor(**kwargs)
  File "/home/ariabi/.local/lib/python3.8/site-packages/allennlp/common/from_params.py", line 467, in constructor
    return value_cls.from_params(params=deepcopy(popped_params), **constructor_extras)
  File "/home/ariabi/.local/lib/python3.8/site-packages/allennlp/common/from_params.py", line 597, in from_params
    return retyped_subclass.from_params(
  File "/home/ariabi/.local/lib/python3.8/site-packages/allennlp/common/from_params.py", line 631, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/home/ariabi/.local/lib/python3.8/site-packages/allennlp/training/trainer.py", line 1295, in from_partial_objects
    else learning_rate_scheduler.construct(
  File "/home/ariabi/.local/lib/python3.8/site-packages/allennlp/common/lazy.py", line 58, in construct
    return self._constructor(**kwargs)
  File "/home/ariabi/.local/lib/python3.8/site-packages/allennlp/common/from_params.py", line 467, in constructor
    return value_cls.from_params(params=deepcopy(popped_params), **constructor_extras)
  File "/home/ariabi/.local/lib/python3.8/site-packages/allennlp/common/from_params.py", line 597, in from_params
    return retyped_subclass.from_params(
  File "/home/ariabi/.local/lib/python3.8/site-packages/allennlp/common/from_params.py", line 631, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/home/ariabi/.local/lib/python3.8/site-packages/allennlp/training/learning_rate_schedulers/slanted_triangular.py", line 75, in __init__
    assert not optimizer.param_groups[-1]["params"], "The default group should be empty."
AssertionError: The default group should be empty.`

Any help is appreciated :)
Thank you in advance.

**Comment by robvanderg** [comment]
Hi Arij!, thanks for the bug report. This can be solved by making the parameter groups more general in params.json, if you replace the last part of "^_text_field_embedder.*.transformer_model.*" it runs. I have updated the default params.json's.

Are you still interested in running with manually specified layers only?

**Comment by ArijRB** [comment]
Hey, Thank you for your quick response. 
Yes for the training with specified layers, I forgot to open an issue sorry.

**Comment by robvanderg** [comment]
I gave it a try, you can check out the 'layers' branch. I do not have a gpu available now to test performance, but from my quick tests on the dimensions it should work. (I would suggest to try it with layer 1 versus -1 first, to see if performance drops)

**Comment by ArijRB** [comment]
Cool, thanks.
